#!/usr/bin/env bash
set -e

if [ "$DEBUG" ]; then
  set -x
fi

function handle_exit () {
    [ $DEBUG ] && echo >&2 "Script exit detected"
    echo "Done"
}


function handle_error () {
    echo >&2 "Script ERROR detected at line $1"
    exit 1;
}

#trap "handle_exit" EXIT
trap 'handle_error ${LINENO}' ERR

function usage() {
    echo ""
    echo "USAGE:"
    echo "        install_from_sinopia [-htdDr] SEMVER"
    echo ""
    echo " -d         : output debug logging"
    echo " -h         : help"
    echo " -D dir     : dir to install version into"
    echo " -t token   : provide npm auth token"
    echo " -r repo    : host:port of npm repo"
    echo " -l         : create local link dt => path to deploy tools"
    echo " -f         : force install a previous version"
    echo ""
    echo "DESCRIPTION:"
    echo "        Will download deploy tools from sinopia and return the path it has downloaded to"
    echo "        You can provide a semantic version https://docs.npmjs.com/misc/semver "
    echo "        The final installation directory will use the actual version downloaded"
    echo "        If that version has previously been downloaded, it will not be replaced without supplying -f"
    echo ""

    if [ "$1" ]; then
        echo "Error: $1"
        echo ""
        exit 1;
    fi
}
base_dir=/var/tmp/deploy_tools

while getopts "ldhD:t:r:" opt; do
  case $opt in
    h)
      usage
      ;;
    d)
      DEBUG=true
      set -x
      ;;
    D)
      base_dir=$OPTARG
      ;;
    t)
      npm_token=$OPTARG
      ;;
    r)
      npm_repo=$OPTARG
      ;;
    l)
      local_link=true
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

shift $(( OPTIND -1  ))
version=$1

if [ -z "$version" ]; then
  usage "No version supplied"
  return 1;
fi

if [ ! -d "$base_dir" ]; then
    [ $DEBUG ] && echo >&2  "$base_dir does not exist, making it"
    mkdir -p "$base_dir"
fi

temp_dir=$(mktemp -d $base_dir/_deploy_tools_XXXXXXXXX)

[ $DEBUG ] && echo >&2 "Installing Deploy Tools version: $version into $temp_dir "

# load nvm if not loaded
echo "Checking NVM"
if type nvm > /dev/null 2>&1 && nvm --version > /dev/null 2>&1; then
    #[ $DEBUG ] && >&2 
    echo "Nvm already loaded"
else
    #[ $DEBUG ] && >&2 
    echo "Loading nvm"
    . ~/.nvm/nvm.sh
fi

X_DT_NODE_VERSION=${X_DT_NODE_VERSION:-6}
echo "Installing/Using node version $X_DT_NODE_VERSION"
nvm install $X_DT_NODE_VERSION
nvm use $X_DT_NODE_VERSION

[ $DEBUG ] && echo >&2 "Node: "$(node -v)  " Npm: " $(npm -v)

# set registry/repo if provided
if [ "$npm_repo" ]; then
    echo >&2 "Setting NPM repo: $npm_repo"
    npm config set registry http://$npm_repo/
fi

# establish value of repo that is set
registry_set=$(grep 'registry\s*='  ~/.npmrc | cut -d= -f2)
[ $DEBUG ] && echo >&2 "Registry: $registry_set"
if [ -z "$registry_set" ]; then
    usage "No registry set (in .npmrc) and npm_repo not provided"
    return 1;
fi

# set token if provided
if [ "$npm_token" ]; then
    [ $DEBUG ] && echo >&2 "Setting Token: $npm_token for repo $registry_set"
    npm set //$registry_set/:_authToken $npm_token
fi

token_reg=$(echo "$registry_set" | cut -d: -f2)
# establish value of token
is_token_set=$(grep authToken ~/.npmrc | grep "$token_reg")
[ $DEBUG ] && echo >&2 "Token: $is_token_set"
if [ -z "$is_token_set" ]; then
    usage "No X_NPM_TOKEN provided or authToken not found in ~/.npmrc"
    return 1;
fi

# initialising temp directory and installing deploy tools using npm
pushd $temp_dir > /dev/null
npm init -y > /dev/null
npm install --save @mol-platform/deploy_tools@${version} > .npminstalllog 2>&1
ln -nsf node_modules/@mol-platform/deploy_tools dt
installed_version=$(npm list --long --parseable |  grep @mol-platform/deploy_tools@  | cut -d: -f2 | sed 's/.*@//')
popd > /dev/null

#if it doesnt exist already or -f (force) supplied, renaming it to the version that was actually downloaded 
if [ -d "$base_dir/$installed_version" ]; then
  [ $DEBUG ] && >&2 ls -l "$base_dir/$installed_version"
  [ $DEBUG ] && >&2 ls -l "$base_dir/$installed_version/node_modules/@mol-platform/deploy_tools/profile"
  [ $DEBUG ] && >&2 ls -l "$base_dir/$installed_version/node_modules/@mol-platform/deploy_tools"
        
  # if empty or force_deploy set..        
  if [ ! -e $base_dir/$installed_version/dt/profile ] || [ $force_deploy ]; then
      rm -rf "$base_dir/$installed_version"
      mv $temp_dir $base_dir/$installed_version
  else
      echo >&2 "WARN: $installed_version already exists, use -f to replace"
      [ $DEBUG ] && >&2 ls -l $base_dir/$installed_version/dt/
      [ $DEBUG ] && >&2 ls -l $base_dir/$installed_version/dt/profile
  fi
else
  mv $temp_dir $base_dir/$installed_version
fi

final_dir=$base_dir/$installed_version

profile_path=$final_dir/dt/profile
[ $DEBUG ] &&  ls -l $final_dir
[ $DEBUG ] &&  ls -l $profile_path

# Do not change the following output as it will be used by calling scripts.
echo "Version: $installed_version"
echo "InstallDir: $final_dir"
echo "ProfilePath: $profile_path"

if [ "$local_link" ]; then 
    [ $DEBUG ] &&  ls -l $final_dir/dt/profile
    [ $DEBUG ] && echo "Creating symlink ./dt => $final_dir/dt"
    ln -nsf $final_dir/dt ./dt
    [ $DEBUG ] &&  ls -l ./dt
    echo "LocalLink: ./dt"
fi
